### ISSUE TITLE
Stored kits dosent work after restarting

### ISSUE THREAD

**Issue by sovtec** [Paradis4432/MicroKits#1]
So when I make kits and try to use them it works fine, but when I restart the server the kits do no longer work, they are still available and show up but does not actually give the kit item when clicked

**Comment by Paradis4432** [comment]
hi thank you for contacting me, i was not able to recreate this issue: https://youtu.be/AZw_iAJrUyE
could you please provide some more information or a video showing whats happening?

**Comment by sovtec** [comment]
> hi thank you for contacting me, i was not able to recreate this issue: https://youtu.be/AZw_iAJrUyE
> 
> could you please provide some more information or a video showing whats happening?

I am not sure what happened, first one kit just became unusable and when I restarted they all became unusable.

We re-installed it, and it has been running fine since, so I am pretty sure this was a user error and that you can close this as solved
