### ISSUE TITLE
Kits not working properly

### ISSUE THREAD

**Issue by sovtec** [Paradis4432/MicroKits#2]
So I have some issues with kits not working properly like bigger kits with more data. Have an example video linked
[imgur](https://i.imgur.com/7WQXzY9.mp4)

https://i.imgur.com/7WQXzY9.mp4

**Comment by Paradis4432** [comment]
i believe thats how its supposed to work, mykits allows you to recreate the kit in case you have all the items of the kit in your inventory. i now see that it would be usefull to be able to create the kit even when you dont have the items, ill check it out

**Comment by sovtec** [comment]
> i believe thats how its supposed to work, mykits allows you to recreate the kit in case you have all the items of the kit in your inventory. i now see that it would be usefull to be able to create the kit even when you dont have the items, ill check it out 

I have a lot of ideas and if you want to do a collab on some new updates I might be able to help. You can add me on disc if you want for further discussion. (98%)#6666

**Comment by Paradis4432** [comment]
sounds great, you dont have friend requests allowed so here my discord: Paradis#4432
